### ISSUE TITLE
The actual scale of the noise 

### ISSUE THREAD

**Issue by banacorn** [campbza/Differentially-private-ANOVA#2]
Thank you for releasing the code, it's really helpful!!

But it got me wondering why is the scale used in the code lower than the upper-bound proved in the paper?
https://github.com/campbza/Differentially-private-ANOVA/blob/eade4c85dbf481eaf3323b4d2af2253e648d3563/anova.py#L45

https://github.com/campbza/Differentially-private-ANOVA/blob/eade4c85dbf481eaf3323b4d2af2253e648d3563/anova.py#L67

**Comment by banacorn** [comment]
Is it because that you've found a better upper-bound!? 😄 
https://github.com/campbza/Differentially-private-ANOVA/commit/a914bf92747275ffc2a6d0df596e699033f211f0

**Comment by globusharris** [comment]
Hi! You are correct, we did find a better upper bound. We actually have a _much_ better version of the test statistic that is better than the one in this code and paper by an order of magnitude. That paper was just resubmitted with edits to PETS, and I can let you know as soon as we have a version up on ArXiV. The code from that isn't really fit for public release yet though.  What are you using the code for? If just for verification that's cool but I want to make sure it's clear that this code is just for measuring the power of the test, not to actually implement it (though with some changes it could). :)

**Comment by banacorn** [comment]
We are comparing the "traditional DP" with DP synthetic data. And ANOVA happens to be one of the test cases.

However, after a few trials yesterday we found that our testing data seems to be too small to be effective in this case (k = 2, n = 1000).
